---
- name: Настроить PROMPT_COMMAND для bash history (универсально)
  hosts: all
  become: yes
  vars:
    config_files:
      - "/etc/bashrc"
      - "/etc/bash.bashrc"
      - "/etc/profile"
      - "{{ ansible_env.HOME }}/.bashrc"
      - "{{ ansible_env.HOME }}/.bash_profile"
    prompt_command_line: 'PROMPT_COMMAND="history -a; history -n"'

  tasks:
    - name: Определить, какие из конфигурационных файлов существуют и доступны для записи
      stat:
        path: "{{ item }}"
        follow: yes
      register: file_stat
      loop: "{{ config_files }}"

    - name: Добавить PROMPT_COMMAND в конец каждого существующего и доступного для записи файла
      lineinfile:
        path: "{{ item.item }}"
        line: '{{ prompt_command_line }}'
        insertafter: EOF
        state: present
        backup: yes
        create: no
      loop: "{{ file_stat.results }}"
      loop_control:
        loop_var: item
      when: item.stat is defined and item.stat.exists and item.stat.writeable
