---
- name: Check wazuh-agent and osquery service status
  hosts: test_vms
  become: yes
  gather_facts: no
  vars:
    services:
      wazuh: wazuh-agent.service
      osquery: osqueryd.service

  tasks:
    - name: Collect service facts
      ansible.builtin.service_facts:
      register: service_facts
      ignore_errors: yes

    - name: Check if wazuh-agent is enabled
      ansible.builtin.command: systemctl is-enabled {{ services.wazuh }}
      register: wazuh_enabled
      changed_when: false
      failed_when: false
      when: service_facts.ansible_facts.services is defined and services.wazuh in service_facts.ansible_facts.services

    - name: Check if osquery is enabled
      ansible.builtin.command: systemctl is-enabled {{ services.osquery }}
      register: osquery_enabled
      changed_when: false
      failed_when: false
      when: service_facts.ansible_facts.services is defined and services.osquery in service_facts.ansible_facts.services

    - name: Set wazuh-agent service status
      ansible.builtin.set_fact:
        wazuh_status: >-
          {{
            'not installed' if service_facts.ansible_facts.services is not defined or services.wazuh not in service_facts.ansible_facts.services
            else service_facts.ansible_facts.services[services.wazuh].state ~ ' (enabled: ' ~ (wazuh_enabled.stdout if wazuh_enabled.stdout is defined else 'unknown') ~ ')'
          }}

    - name: Set osquery service status
      ansible.builtin.set_fact:
        osquery_status: >-
          {{
            'not installed' if service_facts.ansible_facts.services is not defined or services.osquery not in service_facts.ansible_facts.services
            else service_facts.ansible_facts.services[services.osquery].state ~ ' (enabled: ' ~ (osquery_enabled.stdout if osquery_enabled.stdout is defined else 'unknown') ~ ')'
          }}

    - name: Display wazuh-agent status
      ansible.builtin.debug:
        msg: "wazuh-agent on {{ inventory_hostname }} is {{ wazuh_status }}"
      delegate_to: localhost

    - name: Display osquery status
      ansible.builtin.debug:
        msg: "osquery on {{ inventory_hostname }} is {{ osquery_status }}"
      delegate_to: localhost
