---
- name: Check wazuh-agent service status
  hosts: test_vms
  become: yes
  tasks:
    - name: Check if wazuh-agent service exists
      ansible.builtin.command: systemctl is-enabled wazuh-agent
      register: wazuh_enabled
      failed_when: false
      changed_when: false

    - name: Check wazuh-agent service status
      ansible.builtin.command: systemctl is-active wazuh-agent
      register: wazuh_status
      when: wazuh_enabled.rc == 0
      failed_when: false
      changed_when: false

    - name: Display wazuh-agent status
      ansible.builtin.debug:
        msg: >-
          wazuh-agent on {{ inventory_hostname }} is {{ wazuh_status.stdout | default('unknown') }}
          (enabled: {{ wazuh_enabled.stdout | default('not installed') }})
      when: wazuh_enabled.rc == 0

    - name: Display if wazuh-agent is not installed
      ansible.builtin.debug:
        msg: "wazuh-agent is not installed on {{ inventory_hostname }}"
      when: wazuh_enabled.rc != 0
