---
- name: Check wazuh-agent service status
  hosts: test_vms
  become: yes
  gather_facts: no  # Отключаем автоматический сбор фактов
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:
      register: service_facts_result  # Явно регистрируем результат

    - name: Display wazuh-agent status
      ansible.builtin.debug:
        msg: >-
          wazuh-agent on {{ inventory_hostname }} is
          {{
            (service_facts_result.ansible_facts.services['wazuh-agent'] is not defined) |
            ternary('not installed',
              service_facts_result.ansible_facts.services['wazuh-agent'].state ~ ' (enabled: ' ~
              (service_facts_result.ansible_facts.services['wazuh-agent'].enabled | string) ~ ')'
            )
          }}
