---
- name: Install htop on all VMs
  hosts: test_vms
  become: yes
  gather_facts: yes

  tasks:
    - name: Определение ОС
      debug:
        msg: "Это {{ ansible_distribution }}"

    - name: Установка htop (Ubuntu)
      package:
        name: htop
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Установка EPEL + htop (RedOS/CentOS/RHEL)
      package:
        name:
          - epel-release
          - htop
        state: present
      when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'RedOS']
