---
- name: Check wazuh-agent service status
  hosts: test_vms
  become: yes
  gather_facts: no
  vars:
    service_name: wazuh-agent

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:
      register: service_facts_result
      ignore_errors: yes

    - name: Display wazuh-agent status
      ansible.builtin.debug:
        msg: >-
          wazuh-agent on {{ inventory_hostname }} is
          {{
            (service_facts_result.ansible_facts.services is not defined or service_name not in service_facts_result.ansible_facts.services) |
            ternary('not installed',
                    service_facts_result.ansible_facts.services[service_name].state ~ ' (enabled: ' ~
                    service_facts_result.ansible_facts.services[service_name].enabled | string ~ ')')
          }}
      delegate_to: localhost
