---
- name: Check wazuh-agent service status
  hosts: test_vms
  become: yes
  gather_facts: no
  vars:
    service_name: wazuh-agent.service

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:
      register: service_facts_result
      ignore_errors: yes

    - name: Check if wazuh-agent is enabled
      ansible.builtin.command: systemctl is-enabled {{ service_name }}
      register: service_enabled
      changed_when: false
      failed_when: false
      when: service_facts_result.ansible_facts.services is defined and service_name in service_facts_result.ansible_facts.services

    - name: Set wazuh-agent service status
      ansible.builtin.set_fact:
        service_status: >-
          {{
            'not installed' if service_facts_result.ansible_facts.services is not defined or service_name not in service_facts_result.ansible_facts.services
            else service_facts_result.ansible_facts.services[service_name].state ~ ' (enabled: ' ~ (service_enabled.stdout if service_enabled.stdout is defined else 'unknown') ~ ')'
          }}

    - name: Display wazuh-agent status
      ansible.builtin.debug:
        msg: "wazuh-agent on {{ inventory_hostname }} is {{ service_status }}"
      delegate_to: localhost
