---
- name: Установка и настройка Wazuh Agent 4.10.1 на Ubuntu и RedOS
  hosts: test_deploy_wazuh_agent
  become: true
  vars:
    wazuh_manager: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-4.10.1-1.x86_64.rpm"
    wazuh_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb"
    wazuh_rpm_path: "/tmp/wazuh-agent.rpm"
    wazuh_deb_path: "/tmp/wazuh-agent.deb"

  tasks:
    - name: Отладка - вывод информации о дистрибутиве
      debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"

    - name: Проверка доступности Wazuh Manager
      wait_for:
        host: "{{ wazuh_manager }}"
        port: 1514
        timeout: 10
      delegate_to: localhost

    ###########################################################################
    #                          УСТАНОВКА ЗАВИСИМОСТЕЙ                         #
    ###########################################################################

    - name: Установка curl и зависимостей для Debian-based
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
      vars:
        packages:
          - curl
          - apt-transport-https
          - gnupg2
      when: ansible_os_family == "Debian"

    - name: Установка curl для RedHat-based
      yum:
        name: curl
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    ###########################################################################
    #                           УСТАНОВКА НА DEBIAN                           #
    ###########################################################################

    - name: Проверка наличия wazuh-agent на Debian
      command: dpkg -l wazuh-agent
      register: dpkg_check
      failed_when: false
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Скачать DEB-пакет wazuh-agent
      get_url:
        url: "{{ wazuh_deb_url }}"
        dest: "{{ wazuh_deb_path }}"
      when: ansible_os_family == "Debian"

    - name: Установить wazuh-agent через apt
      apt:
        deb: "{{ wazuh_deb_path }}"
        state: present
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "Debian"

    - name: Удалить DEB после установки
      file:
        path: "{{ wazuh_deb_path }}"
        state: absent
      when: ansible_os_family == "Debian"

    ###########################################################################
    #                            УСТАНОВКА НА REDOS                           #
    ###########################################################################

    - name: Проверка наличия wazuh-agent на RedHat/RedOS
      command: rpm -q wazuh-agent
      register: rpm_check
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    - name: Скачать RPM-пакет wazuh-agent
      get_url:
        url: "{{ wazuh_rpm_url }}"
        dest: "{{ wazuh_rpm_path }}"
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    - name: Установить wazuh-agent через yum
      yum:
        name: "{{ wazuh_rpm_path }}"
        state: present
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    - name: Удалить RPM после установки
      file:
        path: "{{ wazuh_rpm_path }}"
        state: absent
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    ###########################################################################
    #                           КОНФИГУРАЦИЯ AGENT                            #
    ###########################################################################

    - name: Проверка наличия ossec.conf
      stat:
        path: /var/ossec/etc/ossec.conf
      register: ossec_conf
      failed_when: not ossec_conf.stat.exists

    - name: Вставка адреса Wazuh Manager в конфиг
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: "<address>{{ wazuh_manager }}</address>"
        backup: yes
      when: ossec_conf.stat.exists

    - name: Вставка группы агента в блок <client>
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- BEGIN ANSIBLE MANAGED BLOCK wazuh-agent group -->\n{mark}\n<!-- END ANSIBLE MANAGED BLOCK wazuh-agent group -->"
        block: |
          <enrollment>
            <enabled>yes</enabled>
            <groups>{{ wazuh_agent_group }}</groups>
            <authorization_pass_path>etc/authd.pass</authorization_pass_path>
          </enrollment>
        insertafter: '<client>'
        backup: yes
      when: ossec_conf.stat.exists

    ###########################################################################
    #                           ЗАПУСК АГЕНТА                                 #
    ###########################################################################

    - name: Перезагрузка systemd
      systemd:
        daemon_reload: true

    - name: Включение и запуск агента Wazuh
      systemd:
        name: wazuh-agent
        enabled: true
        state: started

    - name: Проверка статуса wazuh-agent
      command: systemctl status wazuh-agent
      register: agent_status
      changed_when: false
      failed_when: agent_status.rc != 0
