---
- name: Install and configure Wazuh Agent on Ubuntu and RedOS
  hosts: all
  become: yes
  vars:
    wazuh_manager: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_agent_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb"
    wazuh_agent_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-4.10.1-1.x86_64.rpm"
    reboot_required: false

  tasks:
    - name: Debug - Display OS information
      ansible.builtin.debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"
      delegate_to: localhost

    - name: Set OS facts
      ansible.builtin.set_fact:
        os_family: "{{ ansible_os_family | lower }}"
        is_redos: "{{ ansible_distribution | lower in ['red', 'redos'] }}"

    - name: Install dependencies for Ubuntu
      ansible.builtin.apt:
        name:
          - wget
          - curl
          - gnupg
        state: present
        update_cache: yes
      when: os_family == 'debian'

    - name: Install dependencies for RedOS
      ansible.builtin.dnf:
        name:
          - wget
          - curl
          - gnupg2
        state: present
        update_cache: yes
      when: os_family == 'redhat' or is_redos

    - name: Download Wazuh Agent DEB for Ubuntu
      ansible.builtin.get_url:
        url: "{{ wazuh_agent_deb_url }}"
        dest: "/tmp/wazuh-agent.deb"
        mode: '0644'
      when: os_family == 'debian'

    - name: Install Wazuh Agent on Ubuntu
      ansible.builtin.command:
        cmd: WAZUH_MANAGER={{ wazuh_manager }} WAZUH_AGENT_GROUP={{ wazuh_agent_group }} dpkg -i /tmp/wazuh-agent.deb
      when: os_family == 'debian'
      register: wazuh_install_deb
      changed_when: wazuh_install_deb.rc == 0

    - name: Download Wazuh Agent RPM for RedOS
      ansible.builtin.get_url:
        url: "{{ wazuh_agent_rpm_url }}"
        dest: "/tmp/wazuh-agent.rpm"
        mode: '0644'
      when: os_family == 'redhat' or is_redos

    - name: Install Wazuh Agent on RedOS
      ansible.builtin.dnf:
        name: "/tmp/wazuh-agent.rpm"
        state: present
      when: os_family == 'redhat' or is_redos
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
        WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"

    - name: Clean up downloaded Wazuh Agent DEB
      ansible.builtin.file:
        path: "/tmp/wazuh-agent.deb"
        state: absent
      when: os_family == 'debian'

    - name: Clean up downloaded Wazuh Agent RPM
      ansible.builtin.file:
        path: "/tmp/wazuh-agent.rpm"
        state: absent
      when: os_family == 'redhat' or is_redos

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Wazuh Agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes
        state: started

    - name: Mark system for reboot
      ansible.builtin.set_fact:
        reboot_required: true

    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Rebooting after Wazuh Agent installation"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 300
      when: reboot_required

  handlers:
    - name: Restart Wazuh Agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: restarted
