---
- name: Установка Wazuh Agent 4.10.1 (строго и без переменных окружения)
  hosts: all
  become: true

  vars:
    wazuh_version: "4.10.1"
    wazuh_manager: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_{{ wazuh_version }}-1_amd64.deb"
    wazuh_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-{{ wazuh_version }}-1.x86_64.rpm"

  tasks:
    - name: Покажи инфу про ОС
      debug:
        msg: "Detected OS family: {{ ansible_facts['os_family'] }}, distribution: {{ ansible_facts['distribution'] }}"

    - name: Установка на Debian/Ubuntu
      when: ansible_facts['os_family'] in ["Debian"]
      block:
        - name: Скачать .deb
          get_url:
            url: "{{ wazuh_deb_url }}"
            dest: "/tmp/wazuh-agent.deb"
            mode: '0644'

        - name: Установить .deb
          command: "dpkg -i /tmp/wazuh-agent.deb"
          args:
            creates: /var/ossec

    - name: Установка на RedHat/RedOS
      when: ansible_facts['os_family'] in ["RedHat", "Red", "RED", "RedOS", "Linux"]
      block:
        - name: Скачать .rpm
          get_url:
            url: "{{ wazuh_rpm_url }}"
            dest: "/tmp/wazuh-agent.rpm"
            mode: '0644'

        - name: Установить .rpm
          command: "rpm -ihv /tmp/wazuh-agent.rpm"
          args:
            creates: /var/ossec

    - name: Проверка наличия ossec.conf
      stat:
        path: /var/ossec/etc/ossec.conf
      register: wazuh_conf_check

    - name: Fail если конфиг не найден
      fail:
        msg: "Wazuh agent не установлен! ossec.conf отсутствует!"
      when: not wazuh_conf_check.stat.exists

    - name: Заменить блок <client> в ossec.conf
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '<client>.*?</client>'
        replace: |
          <client>
            <server>
              <address>{{ wazuh_manager }}</address>
            </server>
            <group>{{ wazuh_agent_group }}</group>
          </client>
        backup: yes

    - name: Перезапуск systemd
      systemd:
        daemon_reload: true

    - name: Включить автозапуск wazuh-agent
      systemd:
        name: wazuh-agent
        enabled: true

    - name: Запустить wazuh-agent
      systemd:
        name: wazuh-agent
        state: started
      register: wazuh_start
      failed_when: wazuh_start.failed

    - name: Проверить статус wazuh-agent
      command: systemctl is-active wazuh-agent
      register: wazuh_status
      changed_when: false

    - name: Вывести статус
      debug:
        msg: "Статус wazuh-agent: {{ wazuh_status.stdout }}"

    - name: Показать логи wazuh-agent, если он не активен
      when: wazuh_status.stdout != "active"
      block:
        - name: Собрать последние 50 логов
          command: journalctl -u wazuh-agent --no-pager -n 50
          register: wazuh_logs
          ignore_errors: true

        - name: Показать логи
          debug:
            msg: "{{ wazuh_logs.stdout_lines }}"
