---
- name: Установка и настройка Wazuh Agent 4.10.1 на Ubuntu и RedOS
  hosts: test_deploy_wazuh_agent
  become: yes
  vars:
    wazuh_agent_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb"
    wazuh_agent_deb: "wazuh-agent_4.10.1-1_amd64.deb"
    wazuh_manager_ip: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_agent_pkg_path: "/tmp/{{ wazuh_agent_deb }}"

  tasks:
    - name: Отладка - вывод информации о дистрибутиве
      debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"
      delegate_to: localhost

    - name: Установка зависимостей на Ubuntu
      apt:
        name: wget
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Установка зависимостей на RedOS
      dnf:
        name: wget
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Скачивание пакета wazuh-agent для Ubuntu
      get_url:
        url: "{{ wazuh_agent_url }}"
        dest: "{{ wazuh_agent_pkg_path }}"
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Установка wazuh-agent через dpkg с передачей переменных окружения
      ansible.builtin.command: >
        /bin/bash -c "WAZUH_MANAGER='{{ wazuh_manager_ip }}'
        WAZUH_AGENT_GROUP='{{ wazuh_agent_group }}'
        dpkg -i {{ wazuh_agent_pkg_path }}"
      args:
        creates: /etc/init.d/wazuh-agent
      when: ansible_os_family == "Debian"

    - name: Удаление deb-пакета после установки
      file:
        path: "{{ wazuh_agent_pkg_path }}"
        state: absent
      when: ansible_os_family == "Debian"

    - name: Добавление репозитория Wazuh для RedOS
      yum_repository:
        name: wazuh
        description: Wazuh repository
        baseurl: https://packages.wazuh.com/4.x/yum/
        gpgcheck: yes
        gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Установка wazuh-agent на RedOS
      dnf:
        name: wazuh-agent
        state: present
      when: ansible_os_family == "RedHat"

    - name: Конфигурация wazuh-agent для RedOS (wazuh-manager и группа)
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: "<address>{{ wazuh_manager_ip }}</address>"
        backrefs: yes
      when: ansible_os_family == "RedHat"

    - name: Вставка параметра группировки для RedOS
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        insertafter: '</address>'
        block: |
          <group>{{ wazuh_agent_group }}</group>
      when: ansible_os_family == "RedHat"

    - name: Перезагрузка systemd для обоих дистрибутивов
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Включение агента Wazuh
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    - name: Запуск агента Wazuh
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started
