---
- name: Установка Wazuh Agent 4.10.1 (жестко, без переменных)
  hosts: all
  become: true

  vars:
    wazuh_version: "4.10.1"
    wazuh_manager: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_{{ wazuh_version }}-1_amd64.deb"
    wazuh_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-{{ wazuh_version }}-1.x86_64.rpm"

  tasks:
    - name: Собираем факты
      setup:

    - name: Установка на Ubuntu/Debian через .deb
      when: ansible_facts['os_family'] == "Debian"
      block:
        - name: Скачать .deb
          get_url:
            url: "{{ wazuh_deb_url }}"
            dest: "/tmp/wazuh-agent.deb"
            mode: '0644'

        - name: Установить .deb
          command: "dpkg -i /tmp/wazuh-agent.deb"
          args:
            creates: /var/ossec

    - name: Установка на RedOS/RHEL через .rpm
      when: ansible_facts['os_family'] == "RedHat"
      block:
        - name: Скачать .rpm
          get_url:
            url: "{{ wazuh_rpm_url }}"
            dest: "/tmp/wazuh-agent.rpm"
            mode: '0644'

        - name: Установить .rpm
          command: "rpm -ihv /tmp/wazuh-agent.rpm"
          args:
            creates: /var/ossec

    - name: Прописать менеджера и группу в ossec.conf
      blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: ""
        insertafter: "<client>"
        block: |
          <server>
            <address>{{ wazuh_manager }}</address>
          </server>
          <client>
            <group>{{ wazuh_agent_group }}</group>
          </client>

    - name: Перезапустить systemd
      systemd:
        daemon_reload: true

    - name: Включить автозапуск wazuh-agent
      systemd:
        name: wazuh-agent
        enabled: true

    - name: Запустить wazuh-agent
      systemd:
        name: wazuh-agent
        state: started

    - name: Проверка статуса агента
      command: systemctl is-active wazuh-agent
      register: wazuh_status
      changed_when: false

    - name: Показать статус
      debug:
        msg: "Wazuh agent status: {{ wazuh_status.stdout }}"
