---
- name: Install Wazuh Agent on Linux (RedOS + Ubuntu)
  hosts: 	test_deploy_wazuh_agent
  become: true
  vars:
    wazuh_version: "4.10.1"
    wazuh_manager: "{{ lookup('env', 'WAZUH_MANAGER') | default('192.168.112.160') }}"
    wazuh_agent_group: "{{ lookup('env', 'WAZUH_AGENT_GROUP') | default('new.agents') }}"
  tasks:

    - name: Gather facts
      setup:

    - name: Check OS family
      ansible.builtin.debug:
        msg: "Detected OS family: {{ ansible_os_family }}, distribution: {{ ansible_distribution }}"

    - name: Install Wazuh Agent on RedHat/RedOS
      when: ansible_os_family == "RedHat"
      block:
        - name: Download Wazuh RPM manually
          get_url:
            url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-{{ wazuh_version }}-1.x86_64.rpm"
            dest: "/tmp/wazuh-agent.rpm"

        - name: Install Wazuh Agent with env vars
          ansible.builtin.command: >
            rpm -ihv /tmp/wazuh-agent.rpm
          environment:
            WAZUH_MANAGER: "{{ wazuh_manager }}"
            WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"
          args:
            creates: /var/ossec

    - name: Install Wazuh Agent on Debian/Ubuntu
      when: ansible_os_family == "Debian"
      block:
        - name: Download and install Wazuh APT key
          apt_key:
            url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
            state: present

        - name: Add Wazuh APT repo
          apt_repository:
            repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
            state: present

        - name: Update apt cache
          apt:
            update_cache: true

        - name: Install Wazuh Agent with env
          apt:
            name: wazuh-agent
            state: present
          environment:
            WAZUH_MANAGER: "{{ wazuh_manager }}"
            WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Enable wazuh-agent service
      systemd:
        name: wazuh-agent
        enabled: true

    - name: Start wazuh-agent service
      systemd:
        name: wazuh-agent
        state: started

    - name: Check wazuh-agent status
      command: systemctl is-active wazuh-agent
      register: wazuh_status
      changed_when: false

    - name: Print agent status
      debug:
        msg: "Wazuh agent status: {{ wazuh_status.stdout }}"
