---
- name: Установка и настройка Wazuh Agent 4.10.1 на Ubuntu и RedOS
  hosts: test_deploy_wazuh_agent
  become: true
  vars:
    wazuh_manager: "192.168.112.160"
    wazuh_agent_group: "new.agents"
    wazuh_rpm_url: "https://packages.wazuh.com/4.x/yum/wazuh-agent-4.10.1-1.x86_64.rpm"
    wazuh_deb_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb"
    wazuh_rpm_path: "/tmp/wazuh-agent.rpm"
    wazuh_deb_path: "/tmp/wazuh-agent.deb"

  tasks:

    - name: Отладка - вывод информации о дистрибутиве
      debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}"

    - name: Установка curl для Debian-based
      apt:
        name: curl
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"

    - name: Установка curl для RedHat-based
      yum:
        name: curl
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    ###########################################################################
    #                           УСТАНОВКА НА DEBIAN                           #
    ###########################################################################

    - name: Скачать DEB-пакет wazuh-agent
      get_url:
        url: "{{ wazuh_deb_url }}"
        dest: "{{ wazuh_deb_path }}"
      when: ansible_os_family == "Debian"

    - name: Установить wazuh-agent через dpkg
      command: dpkg -i {{ wazuh_deb_path }}
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "Debian"

    - name: Удалить DEB после установки
      file:
        path: "{{ wazuh_deb_path }}"
        state: absent
      when: ansible_os_family == "Debian"

    ###########################################################################
    #                            УСТАНОВКА НА REDOS                           #
    ###########################################################################

    - name: Скачать RPM-пакет wazuh-agent
      get_url:
        url: "{{ wazuh_rpm_url }}"
        dest: "{{ wazuh_rpm_path }}"
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    - name: Установить wazuh-agent через rpm
      command: rpm -ihv {{ wazuh_rpm_path }}
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    - name: Удалить RPM после установки
      file:
        path: "{{ wazuh_rpm_path }}"
        state: absent
      when: ansible_os_family == "RedHat" or ansible_distribution == "RED"

    ###########################################################################
    #                           КОНФИГУРАЦИЯ AGENT                            #
    ###########################################################################

    - name: Вставка адреса Wazuh Manager в конфиг
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: "<address>{{ wazuh_manager }}</address>"
        backup: yes


    - name: Вставка группы агента в блок <client> (внутрь XML!)
      ansible.builtin.blockinfile:
        path: /var/ossec/etc/ossec.conf
        marker: "<!-- BEGIN ANSIBLE MANAGED BLOCK wazuh-agent group -->\n{mark}\n<!-- END ANSIBLE MANAGED BLOCK wazuh-agent group -->"
        block: |
          <enrollment>
            <enabled>yes</enabled>
            <groups>{{ wazuh_agent_group }}</groups>
            <authorization_pass_path>etc/authd.pass</authorization_pass_path>
          </enrollment>
        insertafter: '<client>'
        backup: yes

    ###########################################################################
    #                           ЗАПУСК АГЕНТА                                 #
    ###########################################################################

    - name: Перезагрузка systemd
      systemd:
        daemon_reload: true

    - name: Включение агента Wazuh
      systemd:
        name: wazuh-agent
        enabled: true
        state: started
