---
- name: Remove Wazuh Agent
  hosts: all
  become: true
  tasks:
    - name: Stop Wazuh Agent
      systemd:
        name: wazuh-agent
        state: stopped
        enabled: false
        ignore_errors: true

    - name: Remove Wazuh Agent on RedHat
      yum:
        name: wazuh-agent
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Wazuh Agent on Debian
      apt:
        name: wazuh-agent
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove agent directory
      file:
        path: /var/ossec
        state: absent
