---
- name: Полное уничтожение Wazuh Agent (деинсталляция, чистка, systemd wipe)
  hosts: all
  become: yes
  tasks:

    - name: Остановить службу wazuh-agent
      systemd:
        name: wazuh-agent
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Удалить wazuh-agent из автозагрузки
      file:
        path: /etc/systemd/system/multi-user.target.wants/wazuh-agent.service
        state: absent
      ignore_errors: true

    - name: Удалить legacy init.d скрипт (если есть)
      file:
        path: /etc/init.d/wazuh-agent
        state: absent
      ignore_errors: true

    - name: Удалить wazuh-agent (Ubuntu/Debian)
      apt:
        name: wazuh-agent
        state: absent
        purge: yes
      when: ansible_facts['os_family'] == 'Debian'
      ignore_errors: true

    - name: Удалить wazuh-agent (RedHat/RedOS)
      yum:
        name: wazuh-agent
        state: absent
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'RED'
      ignore_errors: true

    - name: Удалить /var/ossec
      file:
        path: /var/ossec
        state: absent
      ignore_errors: true

    - name: Удалить ossec сокеты
      file:
        path: /var/run/ossec
        state: absent
      ignore_errors: true

    - name: Удалить systemd unit файл
      file:
        path: /etc/systemd/system/wazuh-agent.service
        state: absent
      ignore_errors: true

    - name: Очистить systemd кеш
      shell: |
        systemctl daemon-reload
        systemctl reset-failed
      changed_when: false
      ignore_errors: true

    - name: Удалить логи Wazuh
      file:
        path: /var/log/ossec.log
        state: absent
      ignore_errors: true

    - name: Подтвердить: агент уничтожен
      debug:
        msg: "Wazuh Agent был полностью уничтожен на {{ inventory_hostname }}"

