---
- name: Полная чистка Wazuh Agent и osquery
  hosts: all
  become: true
  tasks:

    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset: min

    - name: Остановить wazuh-agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Удалить wazuh-agent пакет (DEB)
      ansible.builtin.apt:
        name: wazuh-agent
        state: absent
        purge: yes
      when: ansible_facts['os_family'] == 'Debian'
      ignore_errors: true

    - name: Удалить wazuh-agent пакет (RPM)
      ansible.builtin.yum:
        name: wazuh-agent
        state: absent
      when: ansible_facts['os_family'] in ['RedHat', 'RedOS', 'RED', 'Linux']
      ignore_errors: true

    - name: Удалить osquery пакет (DEB)
      ansible.builtin.apt:
        name: osquery
        state: absent
        purge: yes
      when: ansible_facts['os_family'] == 'Debian'
      ignore_errors: true

    - name: Удалить osquery пакет (RPM)
      ansible.builtin.yum:
        name: osquery
        state: absent
      when: ansible_facts['os_family'] in ['RedHat', 'RedOS', 'RED', 'Linux']
      ignore_errors: true

    - name: Удалить /var/ossec
      ansible.builtin.file:
        path: /var/ossec
        state: absent

    - name: Удалить /etc/init.d/wazuh-agent (если есть)
      ansible.builtin.file:
        path: /etc/init.d/wazuh-agent
        state: absent

    - name: Удалить systemd unit wazuh-agent
      ansible.builtin.file:
        path: /usr/lib/systemd/system/wazuh-agent.service
        state: absent
      ignore_errors: true

    - name: Выполнить systemctl daemon-reload
      ansible.builtin.command: systemctl daemon-reexec

    - name: Сбросить systemctl failed
      ansible.builtin.command: systemctl reset-failed
