---
- name: Main | Configure | syslog-ng | Include agent group config file
  ansible.builtin.include_vars:
    file: siem_agents.yml

- name: Main | Configure | syslog-ng | Adding include option
  ansible.builtin.lineinfile:
    dest: "{{ syslog_ng_config }}"
    line: "@include \"{{ syslog_ng_siem_config }}\""
    firstmatch: yes
    state: present

- name: Main | Configure | syslog-ng | Pushing syslog-ng SIEM config
  ansible.builtin.template:
    src: syslog-ng_10-siem.conf.j2
    dest: "{{ syslog_ng_siem_config }}"
    owner: root
    group: root
    mode: 0600

- name: Main | Configure | syslog-ng | Disabling Auditd log file writing
  when: not auditd_write_logs
  ansible.builtin.replace:
    backup: yes
    path: "{{ syslog_ng_config }}"
    regexp: '(^.+)not facility\(auth,(.*)$'
    replace: '\1not facility(local6,auth,\2'

- name: Main | Configure | syslog-ng | Enabling syslog-ng service
  ansible.builtin.service:
    name: syslog-ng
    enabled: yes

- name: Main | Configure | syslog-ng | Restarting syslog-ng service
  ansible.builtin.service:
    name: syslog-ng
    state: restarted
